version: "3.5"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: pass12
      MYSQL_DATABASE: mobilist
    ports:
      - 3306:3306
    networks:
      - mobilist
  api:
    restart: always
    image: api
    env_file:
      - ./.env
    build:
      context: ./
    container_name: api
    hostname: api
    volumes:
      - ./:/usr/app/mobilist:cached
      - /usr/app/mobilist/node_modules/
    networks:
      - mobilist
    ports:
      - 3000:3000
      - 9231:9231
    depends_on:
      - mysql
networks:
  mobilist:
    name: mobilist-network
volumes:
  esdata:
    driver: local
