const ErrorCodes = Object.freeze({
	UNKNOWN_ERROR: "UNKNOWN_ERROR",
	MISSING_PARAMETERS: "MISSING_PARAMETERS",
	AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	LOGIN_CREDENTIAL_ERROR: "LOGIN_CREDENTIAL_ERROR",
	CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",
});

export default ErrorCodes;
